### ISSUE TITLE
Error running the docker image

### ISSUE THREAD

**Issue by Sp3ci3s8472** [nstapelbroek/estate-crawler#192]
I ran the command provided in the readme:
`docker run --rm -v $(pwd):/app/build docker.io/nstapelbroek/estate-crawler --region amsterdam
`

```
Status: Downloaded newer image for nstapelbroek/estate-crawler:latest
Traceback (most recent call last):
  File "/app/crawler.py", line 9, in <module>
    from estate_crawler.spiders.netherlands import *
  File "/app/estate_crawler/spiders/netherlands.py", line 10, in <module>
    from estate_crawler.util import Extractor, Structure
  File "/app/estate_crawler/util.py", line 4, in <module>
    from htmllaundry import strip_markup
ModuleNotFoundError: No module named 'htmllaundry'
```

**Comment by nstapelbroek** [comment]
hi @Sp3ci3s8472, turns out the docker image was a bit old and is probably not updating automatically anymore. I've pushed a new build manually and this seems to work now. 

```
docker run --rm --pull always -v $(pwd):/app/build docker.io/nstapelbroek/estate-crawler --region amsterdam
latest: Pulling from nstapelbroek/estate-crawler
Digest: sha256:455f910dbc806a97780fcee8998a0f8688f59bd5218c5e305899fdb7aed73e64
Status: Image is up to date for nstapelbroek/estate-crawler:latest
2024-08-05 07:05:23 [scrapy.addons] INFO: Enabled addons:
[]
2024-08-05 07:05:23 [py.warnings] WARNING: /usr/local/lib/python3.12/site-packages/scrapy/utils/request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)
....
```

Let me know if the problem persists
